name: Frontend CI

on: [push, pull_request]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - run: npm ci
      - run: npm run lint    # ESLint must be set up in package.json
      - run: npm test        # Basic test file must exist
